.gitignore, docker-compose.yml, dockerfile
Docker is the best solution for running codes in the machine of the lab or the company without changing its system.
an Example:
- docker-compose build
- docker-compose up -d
- docker-compose exec tensorflowtts /bin/bash
- tmux
- (any operation such as training)
- Ctrl-b d (exit from tmux)
- Ctrl-p Ctrl-q (exit from docker shell)
=> dockerize repository

.gitignore, dockerfile, examples/fastspeech/decode_fastspeech.py, examples/fastspeech/train_fastspeech.py, examples/fastspeech2/decode_fastspeech2.py, examples/fastspeech2/train_fastspeech2.py, examples/melgan.stft/train_melgan_stft.py, examples/melgan/train_melgan.py, examples/multiband_melgan/train_multiband_melgan.py, examples/tacotron2/decode_tacotron2.py, examples/tacotron2/extract_duration.py, examples/tacotron2/train_tacotron2.py
ref. https://github.com/TensorSpeech/TensorflowTTS/issues/80
=> fix path problem

tensorflow_tts/models/fastspeech.py
This commit adds TFLite-convertible logics inside LengthRegulator.
This is tested with `tf-nightly`. 20200630 version. The quantized FastSpeech TFLite file can work with varied-length input & output.
Also,  we fixed the batch_size = 1 during inference. 
In addition, the real problem was the input tensor_spec mismatch inside of `tf.while_loop()`.
the 4th and 5th input tensors are growing (outputs, encoder_masks). this kind of dynamic size (not dynamic shape, please be careful of words. they are different) is not well recommended in TFLite converter. In this assumption, we removed the `tf.while_loop()` during inference as well.
=> 🚀 📝 Add TFLite-convertible TFFastSpeech

examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/MainActivity.java, examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/NumberNorm.java, examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/Processor.java, examples/android/app/src/main/res/layout/activity_main.xml
I implemented the text processors in Android except for the one to expand numbers. I couldn't find out a quick way to implement this functionality without either writing long loops and complicated conditionals, or adding 3rd party libraries as a dependency. What would you suggest for this?
Anyway, other text processors are working nicely, and so I updated UI to accept free text input from the user. If the edit box is empty, then it will inform them about it by speaking a default text.
=> Add text processors and accept free text in Android

examples/tacotron2/extract_duration.py
Looks like there was a typo in #120 :)
=> Fix typo in extract_duration.py

tensorflow_tts/inference/auto_model.py
Reverts TensorSpeech/TensorFlowTTS#175
=> Revert "fix multi-band melgan order"

examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/MainActivity.java, examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/FastSpeech2.java, examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/tts/InputWorker.java, examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/tts/TtsManager.java, examples/android/app/src/main/res/layout/activity_main.xml
allow to choose the audio speed
=> [Android] added speed control

tensorflow_tts/processor/base_processorv2.py, test/files/mapper.json, test/files/train.txt, test/test_base_processor.py
I've fix few bugs in base processor refactor it and add few new features.
You can check it all in base_processorv2 file
Also add few tests
=> refactor processor add test

tensorflow_tts/configs/mb_melgan.py, tensorflow_tts/models/mb_melgan.py
Based-on https://github.com/kan-bayashi/ParallelWaveGAN/pull/204. The model trained on old version is still ok with this change :)).
=> 🔧 Fix pqmf

examples/fastspeech2_libritts/README.md, examples/fastspeech2_libritts/scripts/train_libri.sh, examples/fastspeech2_libritts/train_fastspeech2.py
"preprocess/preprocess_libritts.yaml" does not exist
=> replace "preprocess_libritts.yaml" to "libritts_preprocess.yaml" in the scripts of fastspeech2_libritts

.gitignore, examples/fastspeech/fastspeech_dataset.py, examples/fastspeech2/fastspeech2_dataset.py, examples/fastspeech2_libritts/fastspeech2_dataset.py, examples/melgan/audio_mel_dataset.py, examples/tacotron2/tacotron_dataset.py, tensorflow_tts/bin/preprocess.py
This PR aim to speed-up dataloader by move all read/preprocess data to map function so it can be run parrallel.
=> 🙉 Speedup data loader

examples/fastspeech/conf/fastspeech.v1.yaml, examples/fastspeech/conf/fastspeech.v3.yaml, examples/fastspeech2/README.md, examples/fastspeech2/conf/fastspeech2.baker.v2.yaml, examples/fastspeech2/conf/fastspeech2.kss.v1.yaml, examples/fastspeech2/conf/fastspeech2.kss.v2.yaml, examples/fastspeech2/conf/fastspeech2.v1.yaml, examples/fastspeech2/conf/fastspeech2.v2.yaml, examples/fastspeech2_libritts/conf/fastspeech2libritts.yaml, examples/tacotron2/README.md, examples/tacotron2/conf/tacotron2.baker.v1.yaml, examples/tacotron2/conf/tacotron2.kss.v1.yaml, examples/tacotron2/conf/tacotron2.v1.yaml, tensorflow_tts/trainers/base_trainer.py, test/test_fastspeech2.py, test/test_tacotron2.py
This is a PR to make a base_trainer training on only some layers that the user defines in advance. It's worth to try that we can fine-tune on some layers such as embeddings layers and some last dense layers to let the model transfer from dataset A to dataset B with the same language, processor.
=> Custom trainable variables

examples/mfa_extraction/fix_mismatch.py
Fix for ZeroDivisionError in https://github.com/TensorSpeech/TensorFlowTTS/issues/306
=> Fixed ZeroDivisionError when mfa_longer list is empty

examples/multiband_melgan/conf/multiband_melgan.baker.v1.yaml
fix training mb melgan in baker dataset
=> 🐛 fix training mb melgan in baker dataset

tensorflow_tts/inference/auto_model.py, tensorflow_tts/models/fastspeech.py, test/test_fastspeech.py, test/test_fastspeech2.py
Support resize positional embedding so you can inference longer sentences. Related issue (#410)
@Freddy-pp can you try ? 
```
fastspeech2.resize_positional_embeddings(3000)
fastspeech2.load_weights(..., by_name=True, skip_mismatch=True)
```
=> 🌝 Support FastSpeech resize positional embeddings.

notebooks/Parallel_WaveGAN_TFLite.ipynb
@dathudeptrai 
Adding notebook as discussed [here](https://github.com/TensorSpeech/TensorFlowTTS/issues/458)
=> Adding Parallel WaveGAN Conversion Notebook

tensorflow_tts/trainers/base_trainer.py, tensorflow_tts/utils/utils.py
This makes it possible to write weights file to storages such as GCS and
HDFS.
=> Support writing weights file using tf.io.gfile.

tensorflow_tts/models/hifigan.py
=> 🥀 Correct hifigan resblock logic.

examples/ios/.gitignore, examples/ios/Podfile, examples/ios/Podfile.lock, examples/ios/README.md, examples/ios/TF_TTS_Demo.xcodeproj/project.pbxproj, examples/ios/TF_TTS_Demo/Assets.xcassets/AccentColor.colorset/Contents.json, examples/ios/TF_TTS_Demo/Assets.xcassets/AppIcon.appiconset/Contents.json, examples/ios/TF_TTS_Demo/Assets.xcassets/Contents.json, examples/ios/TF_TTS_Demo/ContentView.swift, examples/ios/TF_TTS_Demo/FastSpeech2.swift, examples/ios/TF_TTS_Demo/Info.plist, examples/ios/TF_TTS_Demo/MBMelGAN.swift, examples/ios/TF_TTS_Demo/Preview Content/Preview Assets.xcassets/Contents.json, examples/ios/TF_TTS_Demo/TF_TTS_DemoApp.swift, examples/ios/TF_TTS_Demo/TTS.swift
Thank you for your great project!
I've put together an example app for iOS.
Please review this pull request.
=> add iOS example

examples/hifigan/conf/hifigan.v1.yaml, examples/hifigan/conf/hifigan.v2.yaml
Sorry for lr typo error.
both loss a '0', which makes model cannot convergence.
sorry for any inconvenience
=> [HiFiGAN] Fix lr error

README.md
easy to use web demo on huggingface spaces using gradio
=> huggingface gradio web demo
